### ISSUE TITLE
Liftover files for my own assemblies? HG002/GRCh37?

### ISSUE THREAD

**Issue by nhansen** [ChaissonLab/TT-Mars#2]
I'm just trying out your new tool and was pleased with how easy it is to run! Can you give guidance on how I would create non-covered and compressed liftover files for my own assemblies? Also, do you plan to make the HG002 assembly and mapping to GRCh37 that you used in your bioRxiv paper public?

Thanks!
--Nancy

**Comment by quentin0515** [comment]
Hi Nancy!
Thanks for your interest on TT-Mars.

> Can you give guidance on how I would create non-covered and compressed liftover files for my own assemblies?

Yes. I'm making some change of the code, and will update you with a script on creating liftover files for your own assemblies soon.

> Also, do you plan to make the HG002 assembly and mapping to GRCh37 that you used in your bioRxiv paper public?

Yes, will also make this dataset public! Will update you when it's ready.

Thanks,
Quentin

**Comment by nhansen** [comment]
Thanks, Quentin! Looking forward to seeing more!

--Nancy

**Comment by quentin0515** [comment]
Hi @nhansen , I have a script describing the steps to generate liftover non-covered region files: [https://github.com/ChaissonLab/TT-Mars/blob/main/liftover.sh](url). Also updated some code to simplify the steps.

Please get the updated version and following the steps to generate your own liftover files:
1. Align assembly to reference by LRA (https://github.com/ChaissonLab/LRA);
2. Trim overlapping contigs;
3. Liftover using trimmed bam files by samLiftover (https://github.com/mchaisso/mcutils);
4. Compress liftover files;
5. Get non-covered regions using trimmed bam files.

Let me know if this works!

Quentin

**Comment by nhansen** [comment]
Thanks again, Quentin. I'll give it a try and let you know!

**Comment by quentin0515** [comment]
You're welcome! The HG002 files are also uploaded, links available in README.

**Comment by viq854** [comment]
Hi Quentin, 

Thanks for developing this useful tool. I'm looking for the HG002 assemblies used in the paper -- but only seeing links to HG002 liftover/coverage files in the README. Are the HG002 assemblies also available? Thanks!
