### ISSUE TITLE
HG002 assemblies

### ISSUE THREAD

**Issue by viq854** [ChaissonLab/TT-Mars#5]
Hi Quentin,

Thanks for developing this useful tool. 

Which HG002 assemblies correspond to the HG002 liftover/coverage files provided in the README (and were analyzed in the manuscript)? 

Thanks!

**Comment by quentin0515** [comment]
Hi Victoria, 

Thanks for the question.
I believe the HG002 assemblies are from hifiasm (https://github.com/chhylp123/hifiasm). The files can be found here: https://zenodo.org/record/4393631. With names NA24385.HiFi.hifiasm-0.12.hap1.fa.gz and NA24385.HiFi.hifiasm-0.12.hap2.fa.gz.
Hope this helps.

Jianzhi (Quentin) Yang

**Comment by viq854** [comment]
Thanks!
